config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  resources :friendships, only: [:create]

  resources :members, only: [:index, :show] do
    get 'my_profile', on: :collection
    post 'topic_experts', controller: 'member_searches'
  end

  root 'members#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :from_member, class_name: 'Member'
  belongs_to :to_member, class_name: 'Member'
end

app/models/member.rb
class Member < ApplicationRecord
  belongs_to :user
  has_many :passions
  has_many :websites

  has_many :from_friendships, class_name: 'Friendship', foreign_key: 'from_member_id'
  has_many :to_friendships, class_name: 'Friendship', foreign_key: 'to_member_id'
  has_many :from_members, through: :to_friendships
  has_many :to_members, through: :from_friendships

  validates :full_name, presence: true

  def friends
    # TODO: single query
    from_members + to_members
  end

  # All members who could be added as a friend.
  def elligible_friends
    # TODO: single query
    Member.where.not(id: id) - friends
  end
end

app/models/passion.rb
class Passion < ApplicationRecord
  belongs_to :member
  belongs_to :website
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/website.rb
class Website < ApplicationRecord
  belongs_to :member
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def after_sign_in_path_for(_resource)
    my_profile_members_path
  end
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  def create
    Friendship.create!(friendship_params)
    redirect_to my_profile_members_path
  end

  private

  # Only allow a list of trusted parameters through.
  def friendship_params
    params.require(:friendship).permit(:from_member_id, :to_member_id)
  end
end

app/controllers/member_controller.rb
class MemberController < ApplicationController
  def my_profile
    @member = Member.eager_load(:passions, :websites).find_by(user: current_user)
  end

  def show
    @member = Member.eager_load(:passions, :websites).find(params[:id])
  end
end

app/controllers/member_searches_controller.rb
class MemberSearchesController < ApplicationController
  def topic_experts
    from_member_id = params[:member_id]
    @topic = params[:topic]
    @introductions = Searches::TopicSearch.new(@topic, from_member_id).call
  end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  def index
    @members = Members::AllMemberPreviews.new.call
  end

  def my_profile
    @member = member_profile_page_scope.find_by(user: current_user)
  end

  def show
    @member = member_profile_page_scope.find(params[:id])
  end

  private

  def member_profile_page_scope
    Member.eager_load(
      :passions,
      :websites,
      :from_members,
      :to_members
    )
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  def create
    super
    member = Member.create(
      full_name: params[:member][:full_name],
      user: current_user
    )
    website = Websites::WebsiteBuilder.new(
      params[:website][:full_url],
      member: member
    ).call
    Websites::PassionsFactory.new(member, website).call
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    my_profile_members_path
  end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/friendships/_form.html.erb
<%= form_for friendship do |f| %>
  <%= f.hidden_field :from_member_id %>

  <%= f.label :to_member_id %>
  <%= f.collection_select :to_member_id, elligible_friends, :id, :full_name %>

  <%= f.submit 'Add Friend' %>
<% end %>

app/views/friendships/_list.html.erb
<ul>
  <% friends.each do |friend| %>
    <li><%= link_to friend.full_name, member_path(friend) %>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WhySpace</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <hr>
    <footer>
      <% if user_signed_in? %>
        <%= link_to('My Profile', my_profile_members_path) %>
        <%= button_to('Logout', destroy_user_session_path, method: :delete) %>
      <% else %>
        <%= button_to 'Join Now', new_user_registration_path, method: :get %>
        <%= button_to 'Already a Member', new_user_session_path, method: :get %>
      <% end %>
    </footer>
  </body>
</html>

app/views/member_searches/_introduction_links.html.erb
<%= introduction.members.map do |member| %>
  <% link_to member.full_name, member_path(member) %>
<% end.join(' > ').html_safe %>

app/views/member_searches/_topic_experts_form.html.erb
<%= form_with url: member_topic_experts_path(member), local: true do |f| %>
  <%= f.label :topic %>
  <%= f.text_field :topic %>

  <%= f.submit 'Find Experts' %>
<% end %>

app/views/member_searches/topic_experts.html.erb
<h1>Topic Experts Search Results</h1>

<% if @introductions.none? %>
  Sorry we couldn't find any friends of friends who can introduce you to experts in <b>"<%= @topic %>"</b>.
<% else %>
  Friends of friends who can introduce you to experts in <b>"<%= @topic %>"</b>...
  <ul>
    <% @introductions.each do |introduction| %>
      <li>
        <%= render partial: 'introduction_links', locals: { introduction: introduction } %>
        (<%= introduction.topic %>)
      </li>
    <% end %>
  </ul>
<% end %>

app/views/members/_member_preview.html.erb
<p>
  <%= link_to member_preview.full_name, member_path(member_preview.member_id) %>
  <%= member_preview.short_url %>
  (<%= member_preview.friend_count %> friends)
</p>

app/views/members/_passions_list.html.erb
<ul>
  <% passions.each do |passion| %>
    <li><%= passion.topic %></li>
  <% end %>
</ul>

app/views/members/_websites_list.html.erb
<% websites.each do |website| %>
  <p>Website: <%= link_to website.full_url, website.full_url %> (<%= link_to website.short_url, website.short_url %>)<p>
<% end %>

app/views/members/index.html.erb
<h1>Why Space Members</h1>

<%= render partial: "member_preview", collection: @members %>

app/views/members/my_profile.html.erb
<h1>My Profile</h1>

<p>Name: <%= @member.full_name %><p>

<%= render partial: 'websites_list', locals: { websites: @member.websites } %>

<h2>My Topics of Interest</h2>

<%= render partial: 'passions_list', locals: { passions: @member.passions } %>

<h2>My Friends</h2>

<%= render partial: 'friendships/list', locals: {
  friends: @member.friends
} %>

<%= render partial: 'friendships/form', locals: {
  friendship: @member.from_friendships.new,
  elligible_friends: @member.elligible_friends
} %>

<%= render partial: 'member_searches/topic_experts_form', locals: { member: @member } %>

app/views/members/show.html.erb
<h1><%= @member.full_name %></h1>

<%= render partial: 'websites_list', locals: { websites: @member.websites } %>

<h2>Topics of Interest</h2>

<%= render partial: 'passions_list', locals: { passions: @member.passions } %>

<h2>Friends</h2>

<%= render partial: 'friendships/list', locals: {
  friends: @member.friends
} %>